name: Little Kidogo Interruption Parser
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.5]

    steps:
    - uses: actions/checkout@v2
    - name: Set Up Python ${{matrix.python-version}}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run : |
       python -m pip install --upgrade pip
       pip install -r requirements.txt


#compiling the code into an executable
   compile:
    runs-on: windows-latest
    steps:
    - name: Compile code
      run: |
       pip install PyInstaller
       pyinstaller --onefile manage.py
      
